# Generated by Django 5.1.6 on 2025-02-18 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('location_type', models.CharField(choices=[('0', 'a Village'), ('1', 'a Castle'), ('2', 'a Hamlet'), ('3', 'a Town'), ('4', 'a City'), ('5', 'a Fortress'), ('6', 'a Keep'), ('7', 'a Citadel'), ('8', 'a Tower'), ('9', 'Ruins'), ('10', 'a Monastery'), ('11', 'a Temple'), ('12', 'a Sanctuary'), ('13', 'an Academy'), ('14', 'a Library'), ('15', 'a Market'), ('16', 'a Harbor'), ('17', 'an Inn'), ('18', 'a Mine'), ('19', 'a Cavern'), ('20', 'a Dungeon'), ('21', 'a Swamp'), ('22', 'a Forest'), ('23', 'a Glade'), ('24', 'a Meadow'), ('25', 'a Mountain'), ('26', 'a Valley'), ('27', 'a Desert'), ('28', 'a Tundra'), ('29', 'an Isle'), ('30', 'an Archipelago'), ('31', 'a Crypt'), ('32', 'Catacombs')], default='0', max_length=2)),
                ('description', models.TextField(max_length=500)),
                ('is_visited', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.quest')),
            ],
        ),
    ]
