# Generated by Django 5.1.6 on 2025-02-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_type', models.CharField(choices=[('0', 'Dungeon Crawl'), ('1', 'Mystery Investigation'), ('2', 'Monster Hunt'), ('3', 'Political Intrigue'), ('4', 'Exploration Quest'), ('5', 'Heist Mission'), ('6', 'Rescue Operation'), ('7', 'Escort Duty'), ('8', 'Survival Challenge'), ('9', 'War Campaign'), ('10', 'Siege Defense'), ('11', 'Assassination Plot'), ('12', 'Artifact Recovery'), ('13', 'Arena Combat'), ('14', 'Rogues Gambit'), ('15', 'Fey Bargain'), ('16', 'Plague Outbreak'), ('17', 'Time Loop'), ('18', 'Underworld Dealings'), ('19', 'Divine Trial')], default='0', max_length=2)),
            ],
        ),
    ]
