# Generated by Django 5.1.6 on 2025-02-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.quest'),
            preserve_default=False,
        ),
    ]
