# Generated by Django 5.1.6 on 2025-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_session_quest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='quest',
        ),
        migrations.AddField(
            model_name='quest',
            name='locations',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
