# Generated by Django 5.1.6 on 2025-03-13 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_quest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='npcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hitpoints', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('armor_class', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('backstory', models.TextField(max_length=500)),
                ('npc_type', models.CharField(choices=[('0', 'Innkeeper'), ('1', 'Merchant'), ('2', 'Blacksmith'), ('3', 'Guard'), ('4', 'Noble'), ('5', 'Peasant'), ('6', 'Bounty Hunter'), ('7', 'Bandit'), ('8', 'Alchemist'), ('9', 'Healer'), ('10', 'Priest'), ('11', 'Cultist'), ('12', 'Wizard'), ('13', 'Sorcerer'), ('14', 'Druid'), ('15', 'Bard'), ('16', 'Rogue'), ('17', 'Ranger'), ('18', 'Knight'), ('19', 'Paladin'), ('20', 'Warlock'), ('21', 'Necromancer'), ('22', 'Scholar'), ('23', 'Sailor'), ('24', 'Pirate'), ('25', 'Hunter'), ('26', 'Farmer'), ('27', 'Fisherman'), ('28', 'Stablemaster'), ('29', 'Mayor'), ('30', 'King'), ('31', 'Queen'), ('32', 'Prince'), ('33', 'Princess'), ('34', 'General'), ('35', 'Captain'), ('36', 'Spy'), ('37', 'Beggar'), ('38', 'Minstrel'), ('39', 'Hermit'), ('40', 'Gladiator'), ('41', 'Executioner'), ('42', 'Gravekeeper'), ('43', 'Smuggler'), ('44', 'Assassin'), ('45', 'Seer'), ('46', 'Chieftain'), ('47', 'Beastmaster'), ('48', 'Tavern Wench'), ('49', 'Messenger')], default='0', max_length=2)),
                ('is_alive', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.location')),
            ],
        ),
    ]
