# Generated by Django 5.1.6 on 2025-03-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_npcs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='npcs',
            new_name='NPC',
        ),
    ]
